# Herramientas computacionales para solucionar PDEs

### Juan S. Hincapié - Carlos Duque-Daza

## Bienvenidos a la segunda parte del curso

<div align='justify'>Hasta este momento del curso "sólo" hemos estudiado las ecuaciones diferenciales ordinarias... y digo "sólo" porque en realidad, detrás de esta primera parte hemos recorrido mucho camino: reforzamos los conceptos de adimensionalización, al igual que los principios de conservación de masa y de momento, también desarrollamos modelos para tanques interconectados, vaciado de tanques y sistemas mecánicos, y no olvidemos los conceptos de estabilidad. Pues bien, ya es hora de dar un paso más, ¿Cómo? Pues estudiando las ecuaciones diferenciales parciales (EDPs), sólo así podremos completar nuestra formación como modeladores matemáticos juniors. </div>
<br>

<div align='justify'>Para empezar con el pie derecho en esta segunda parte, debemos pasar primero por una capacitación. Así es: debemos aprender una serie de herramientas y técnicas de programación para no salir tan mal heridos de esta parte del curso. El contenido es el siguiente:</div>

1. Refuerzo vectores
1. Refuerzo matrices
1. ¿Cómo llenar una matriz que presenta un patrón?
1. Resolver sistema de ecuaciones lineales

$\color{RoyalBlue}{\LARGE{\textbf{Refuerzo de vectores}}}$

<div align='justify'>Los vectores, matrices y la operación entre ellos es esencial para la solución de modelos matemáticos ¿Qué nos ofrece Python para este aspecto? Pues bien tenemos la librería Numpy, una biblioteca que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. Lo primero que debemos hacer es importarla. Echemosle un vistazo: </div>

In [2]:
import numpy as np

Podemos crear vectores y operar con ellos:

In [4]:
# Crear el vector de forma "tradicional"
vector1 = np.array([1, 2, 3, 4, 5])

# ¿Será posible crear un vector con range?
vector2 = np.array(range(6,1,-1))

# Sume los dos vectores
print(vector1 + vector2)

[7 7 7 7 7]


$\color{RoyalBlue}{\large{\textbf{Operaciones: producto punto y producto elemento por elemento}}}$

<div align='justify'>Cree dos vectores, $v_1$ y $v_2$ de $1\times 5$. Con estos dos vectores plantee las siguientes operaciones e imprima sus resultados: </div>

1. Haga la multiplicación elemento por elemento e imprima el resultado.
1. Haga el producto punto

In [3]:


#Multiplicación elemento por elemento
    
#Producto punto, o interno

[ 6 14 24 36 50]
130


$\color{RoyalBlue}{\large{\textbf{Ejercicio 01}}}$

<div align='justify'>Un fabricante de joyería de diseño tiene órdenes por dos anillos, tres pares de aretes, cinco prendedores y un collar. El fabricante estima que le llevará 1 hora de mano de obra hacer un anillo, 1 1/2 horas hacer un par de aretes, 21 hora para un prendedor y 2 horas para un collar.</div>


1. Exprese las órdenes del fabricante como un vector fila.
1. Exprese los requerimientos en horas para los distintos tipos de joyas como un vector fila.
1. Utilice el producto punto para calcular el número total de horas que requerirá paraterminar las órdenes.
1. Utilize el producto elemento por elemento para calcular el tiempo que tarda en fabricar cada uno de los productos, es decir, cuánto tarda en producir los dos anillos, cuánto demora en los tres pares de aretes... etc.

El fabrica tarda 113.50 horas para tener listo todo el pedido
Anillos 2.00 horas
Aretes 4.50 horas
Prendedores 105.00 horas
Collar 2.00 horas 


$\color{RoyalBlue}{\large{\textbf{Ejercicio 02}}}$

<div align='justify'>Un turista regresó de un viaje por América del Sur con divisa extranjera de las siguientes denominaciones: 1000 pesos argentinos, 20 reales de Brasil, 100 pesos colombianos, 5000 pesos chilenos y 50 colones de Costa Rica. En dólares, un peso argentino valía $\$$0.3174, los reales brasileños $\$$0.4962, los pesos colombianos $\$$0.000471, los pesos chilenos $\$$0.00191 y los colones $\$$0.001928.</div>



1. Exprese la cantidad de cada tipo de moneda por medio de un vector fila
1. Exprese el valor de cada tipo de moneda en dólares por medio de un vector fila.
1. Utilice el producto escalar para calcular cuántos dólares valía el dinero extranjero del
turista

337.01750000000004


$\color{RoyalBlue}{\large{\textbf{Llamar elementos de un vector}}}$

<div align='justify'> Cree un vector que tenga los números enteros desde el 1 hasta el 5.</div>


In [31]:

print(vector1)

[1 2 3 4 5]


<div align='justify'>¿Cómo haría para llamar al primer elemento del vector?</div>


1


<div align='justify'>¿Y cómo llamaría al último elemento del vector?</div>


5


También podemos conocer el número de elementos que contiene un vector usando la siguiente función:

5


$\color{RoyalBlue}{\large{\textbf{Ejercicio 03}}}$
<div align='justify'> Escriba un código en el que se solicita 5 número a un usuario y se deben almacenar en un vector. Al final se debe imprimir el vector.</div>



In [34]:
#Esta función nos permite reservar memoria para el vector, creando un vector de ceros:


Ingrese un número: 1
Ingrese un número: 2
Ingrese un número: 4
Ingrese un número: 5
Ingrese un número: 6
[1. 2. 4. 5. 6.]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 04}}}$

<div align='justify'> Escribe un programa que muestre sólo aquellos números de una lista que cumplan las siguientes condiciones:</div>

1. El número debe ser divisible por cinco
1. El número debe ser mayor a 50.
1. El número debe ser menor a 500

In [33]:
numeros = np.array([12, 75, 150, 180, 145, 525, 50])

#Debemos iterar sobre los número de la lista. 
#Propongo una manera:


75
150
180
145


$\color{RoyalBlue}{\LARGE{\textbf{Refuerzo matrices}}}$


<div align='justify'> Miremos como se puede crear una matriz:</div>

In [4]:
M = np.array([[3,4,-1],[2,0,1],[1,3,-2]])
print(M)

[[ 3  4 -1]
 [ 2  0  1]
 [ 1  3 -2]]


$\color{RoyalBlue}{\large{\textbf{Operaciones con matrices}}}$
<div align='justify'> Podemos sacar la inversa de la matriz:</div>

In [5]:
M_inv = np.linalg.inv(M)
print(M_inv)

# ¿Cómo verificamos que es la inversa?


[[-0.6  1.   0.8]
 [ 1.  -1.  -1. ]
 [ 1.2 -1.  -1.6]]
[[ 1.00000000e+00 -3.33066907e-16 -2.22044605e-16]
 [ 2.22044605e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]
[[ 1.00000000e+00 -3.33066907e-16 -2.22044605e-16]
 [ 2.22044605e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]


In [19]:
M_tr = np.transpose(M)
print(M_tr)
# ¿Cómo verificamos que es la transpuesta?

[[ 3  2  1]
 [ 4  0  3]
 [-1  1 -2]]


In [20]:
#¿Será que el determinante es diferente de cero? ¿Cómo saberlo?
M_det = np.linalg.det(M)
print(M_det)

5.000000000000003


$\color{RoyalBlue}{\large{\textbf{Ejercicio 05}}}$

<div align='justify'>Una fábrica de muebles de calidad tiene dos divisiones: un taller de máquinas herramienta donde se fabrican las partes de los muebles, y una división de ensamble y terminado en la que se unen las partes para obtener el producto final. Suponga que se tienen $12$ empleados en el taller y $20$ en la división y que cada empleado trabaja $8$ horas. Suponga también que se producen únicamente dos artículos: sillas y mesas. Una silla requiere $384/17$ horas de maquinado y $480/17$ horas de ensamble y terminado. Una mesa requiere $240/17$ horas de maquinado y $640/17$ horas de ensamble y terminado. Suponiendo que se tiene una demanda ilimitada de estos productos y que el fabricante desea mantener ocupados a todos sus empleados, ¿cuántas sillas y cuántas mesas puede producir esta fábrica al día? </div>

$x$: Número de sillas $y$: Número de mesas

\begin{align*}
    & \frac{384}{17}x + \frac{240}{17}y = 8 \times 12 \\
    & \frac{480}{17}x + \frac{640}{17}y = 8 \times 20
\end{align*}

Con las funciones que hemos visto hasta ahora, ¿Cómo podríamos resolver este problema?

[[22.58823529 14.11764706]
 [28.23529412 37.64705882]]
[[ 96]
 [160]]


[[3.]
 [2.]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 06}}}$

<div align='justify'>La alacena de ingredientes mágicos de una hechicera contiene $10$ onzas de tréboles de
cuatro hojas molidos y $14$ onzas de raíz de mandrágora en polvo. La alacena se resurte en forma automática siempre y cuando ella termine con todo lo que tiene. Una poción para entender Python requiere $3 \frac{1}{13}$ onzas de tréboles y $2~\frac{2}{13}$ onzas de mandrágora. Una receta de un conocido tratamiento para poder plantear modelos matemáticos como Alfio Quarteroni   requiere $5~\frac{5}{13}$ onzas de tréboles y $10~\frac{10}{13}$ onzas de mandrágora. ¿Qué cantidad de la poción para entender Python y del remedio para modelar matemáticamente se debe combinar para usar toda la reserva en su alacena?</div>

$x$: poción para enteder Python $y$: poción para plantear modelos matemáticos

\begin{align*}
    & \frac{40}{13}x + \frac{70}{13}y = 10 \\
    & \frac{28}{13}x + \frac{140}{13}y = 14
\end{align*}


[[ 3.07692308  5.38461538]
 [ 2.15384615 10.76923077]]
[[10]
 [14]]
[[1.5]
 [1. ]]


¿ Cómo verifica que el resultado es el correcto?

[[10.]
 [14.]]


$\color{RoyalBlue}{\LARGE{\textbf{¿Cómo llenar una matriz que presenta un patrón?}}}$

$\color{RoyalBlue}{\large{\textbf{Índices de una matriz}}}$


<div align='justify'>Los elementos de una matriz, al igual que con los vectores, tienen unos índices que los indentifican ¿Cuál es la lógica de los índices?</div>


In [14]:
F = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(F[0,0])

1


In [63]:
print(F[2,2]) #¿Por qué no es F[3,3]?

9


¿De qué otra manera se podría imprimir el último elemento de la matriz?

9


¿Qué haría para imprimir toda la segunda fila de la matriz F?

[4 5 6]


¿Qué haría para imprimir únicamente la segunda columna?

[2 5 8]


¿Será lo mismo emplear $F[1,:-1]$ que $F[1,:]$?

$\color{RoyalBlue}{\large{\textbf{Ciclo for para recorrer la matriz}}}$

<div align='justify'>Saber cómo ingresar en las "entrañas" es muy importante para poder implementar métodos númericos en código. Por ejemplo, para ingresar condiciones de frontera de una EDP. Por ahora, nos esforzaremos por "agarrar" la lógica de los recorridos usando ciclos For.</div>

In [90]:
H = np.array([[1,2,3],[4,5,6],[7,8,9]])*1.5
print(H)

[[ 1.5  3.   4.5]
 [ 6.   7.5  9. ]
 [10.5 12.  13.5]]


Tenemos muchas opciones para recorrer una matriz; pero acá les voy a presentar únicamente una. Si entendemos esta primera lógica, entender las demás será "papita pal loro."

In [93]:
#Podemos obtener primero las dimensiones de una matriz con la siguiente función
row, col = H.shape
#Construimos un primer ciclo for que irá fila por fila
for r in range(0,row,1):
    #Pero antes de pasar a la siguiente fila, tendrá que pasar por todas las columnas
    for c in range(0,col,1):
        #¿Cómo saber si estamos recorriendo la matriz como pensábamos? ¡Print!
        print(H[r, c], end = " ")
    print("")

1.5 3.0 4.5 
6.0 7.5 9.0 
10.5 12.0 13.5 


$\color{RoyalBlue}{\large{\textbf{Identificar patrón}}}$

<div align='justify'> Los sistemas de ecuaciones que surgen en las soluciones numéricas de las EDPs unidimensionales presentan matrices con patrones que se identifican a simple vista. Es importantísimo llenar la matriz siguiendo dicho patrón con el fin de resolver dicho sistema computacionalmente. </div>


$\color{RoyalBlue}{\large{\textbf{Ejercicio 07:}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l}
    {1}&{0}&{0}\\ 
    {0}&{1}&{0}\\ 
    {0}&{0}&{1}
    \end{array}\right)}
$$


In [32]:
B = np.zeros((3,3), dtype = int)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
row, col = B.shape
for r in range(row):
    for c in range(col):
        if  r == c :
            B[r, c] = 1
print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 08: semi - legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {0}&{1}&{0}&{0}&{0}\\ 
    {1}&{0}&{1}&{0}&{0}\\ 
    {0}&{1}&{0}&{1}&{0}\\
    {0}&{0}&{1}&{0}&{1}\\
    {0}&{0}&{0}&{1}&{0}
    \end{array}\right)}
$$

In [3]:
S = np.zeros((5,5), dtype = int)


[[0 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 09: semi - plus - legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {5}&{1}&{0}&{2}&{0}\\ 
    {1}&{5}&{1}&{0}&{2}\\ 
    {0}&{1}&{5}&{1}&{0}\\
    {2}&{0}&{1}&{5}&{1}\\
    {0}&{2}&{0}&{1}&{5}
    \end{array}\right)}
$$

In [18]:
S = np.zeros((5,5), dtype = int)


[[5 1 0 2 0]
 [1 5 1 0 2]
 [0 1 5 1 0]
 [2 0 1 5 1]
 [0 2 0 1 5]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 10: legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {1}&{2}&{2}&{2}&{2}\\ 
    {2}&{1}&{0}&{0}&{2}\\ 
    {2}&{0}&{1}&{0}&{2}\\
    {2}&{0}&{0}&{1}&{2}\\
    {2}&{2}&{2}&{2}&{1}
    \end{array}\right)}
$$


In [5]:
B = np.zeros((5,5), dtype = int)



[[1 2 2 2 2]
 [2 1 0 0 2]
 [2 0 1 0 2]
 [2 0 0 1 2]
 [2 2 2 2 1]]


$\color{RoyalBlue}{\LARGE{\textbf{Resolver sistema de ecuaciones lineales}}}$

$\color{RoyalBlue}{\large{\textbf{Ejercicio 11: }}}$

$$
\left[\begin{array}{rrrrr}
375 & -125 & 0 & 0 & 0 \\
-125 & 250 & -125 & 0 & 0 \\
0 & -125 & 250 & -125 & 0 \\
0 & 0 & -125 & 250 & -125 \\
0 & 0 & 0 & -125 & 375
\end{array}\right]\left[\begin{array}{l}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_5
\end{array}\right]=\left[\begin{array}{r}
29000 \\
4000 \\
4000 \\
4000 \\
54000
\end{array}\right]
$$


Este debería ser el resultado:

$$
\left[\begin{array}{l}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_5
\end{array}\right]=\left[\begin{array}{l}
150 \\
218 \\
254 \\
258 \\
230
\end{array}\right]
$$